### ISSUE TITLE
Default GPOs are created with "server" not respecting the configured servername

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#159]
When using a different name for server this is no respected when creating the gpos.

![grafik](https://user-images.githubusercontent.com/26460239/177610669-3eb3bcc8-d9e1-4583-b957-8cd9e28feb36.png)

In this case servername should be srv instead of server

Further information:
https://ask.linuxmuster.net/t/server-oder-logonserver-oder-srv/9008

**Comment by jeffbeck** [comment]
I cannot find a single textfile in the GPO or /var/lib/samba


I think this is fixed long time ago

**Comment by PLanB2008** [comment]
This is not fixed. When a user tries to set a servernamen different from "server" the GPO is created with server as a servername anyway.

**Comment by jeffbeck** [comment]
i just created the gpo on my system. There is just the name of my testserver, but not the string 'server'

**Comment by PLanB2008** [comment]
https://ask.linuxmuster.net/t/server-oder-logonserver-oder-srv/9008

This happened just a month ago. Maybe this is just for the initial creation of the gpo?
