### ISSUE TITLE
Moving a device from one room to another not possible

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#85]
Scenario:

Computer object  in device csv:

r301;r301-pc01 ...

Now I realize I need this computer in room r201 so I change the entry to r201;r201-pc01 and run linuxmuster-import-devices but in AD the computer keeps the ou it is in.

**Comment by jeffbeck** [comment]
This is fixed in earlier Versions of sophomorix

**Comment by PLanB2008** [comment]
Hi Rüdiger,

accoding to https://ask.linuxmuster.net/t/computer-werden-nicht-verschoben-wenn-man-diesen-einen-neuen-raum-zuweist/9788

this is still an issue. Could you look into it?

Regards,
andy
